---
title: "About Me"
output: html_document

author: Rishabh
images: ~
---

I work at a boutique management consultancy which specialises in behavioural and data science. Working with clients across sectors from telecom to financial to media has given me immense understanding about applying behavioural and data science to improve products and services. 

My colleagues would describe me as a sociable and entrepreneurial person. Last year I conceptualised and organised an event bringing in new and older clients to share the latest thinking in behavioural science. Before this, I have created a training programme for budding entrepreneurs to develop their business ideas suitably. I presented this programme at national UKCISA conference. 

I am from India and in 2014 moved to the UK when I was awarded a merit scholarship to study economics at the University of Sheffield. Throughout my undergraduate degree, I developed a reflective mindset and found that pure economics was trying to understand humans by relying too much on mathematical models than just observing human behaviour. Thus, in 2017 I pursued a masters in behavioural and economics sciences at Warwick University after getting a merit scholarship. Here, I learnt about what causes human behaviour, how it can be influenced and how data can help in identifying various nuances in people's decisions. I am one of a few lucky ones who get to practice what they learnt and I enjoy it very much!

Beyond my academic and professional life, I try to make a difference. During my bachelors, I had led my University's minority student groups. At Warwick, I co-founded Warwick Behavioural Insights Team - an organisation which applied behavioural science to improve student wellbeing and reduce theft. 

Personal and professional development at the core of my personality; whether that be my technical abilities, in personal projects such as learning a new language (español), I am always determined to go above and beyond my goals for continuous improvement. 

You can find me on Twitter: @RishabhKumar_ or get in touch at rishkr144@gmail.com. 